# Setup
title:        Gunmin Lee's Atelier
tagline:      Research interest in Autonomous Driving and Robotics
baseurl:      ""
paginate:     1
locale:       "en"
future:       true

# About/contact
author: 
  name: Gunmin Lee
  url:  https://kevin647.github.io//


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
